/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDock: typeof import('./src/components/layout/AppDock.vue')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ChildTable: typeof import('./src/components/common/ChildTable.vue')['default']
    Column: typeof import('primevue/column')['default']
    ContextMenu: typeof import('primevue/contextmenu')['default']
    CreateDialog: typeof import('./src/components/dialogs/CreateDialog.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DeleteDialog: typeof import('./src/components/dialogs/DeleteDialog.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dock: typeof import('primevue/dock')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    EditableField: typeof import('./src/components/common/EditableField.vue')['default']
    EditableFieldset: typeof import('./src/components/common/EditableFieldset.vue')['default']
    EditDialog: typeof import('./src/components/dialogs/EditDialog.vue')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    FormField: typeof import('./src/components/common/FormField.vue')['default']
    Galleria: typeof import('primevue/galleria')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Layout: typeof import('./src/components/layout/Layout.vue')['default']
    LeadInfoTab: typeof import('./src/components/leads/tabs/LeadInfoTab.vue')['default']
    LeadList: typeof import('./src/components/leads/LeadList.vue')['default']
    LeadPane: typeof import('./src/components/leads/LeadPane.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Panel: typeof import('primevue/panel')['default']
    PhonebookTab: typeof import('./src/components/leads/tabs/PhonebookTab.vue')['default']
    PhonebookTable: typeof import('./src/components/leads/tabs/PhonebookTable.vue')['default']
    PreferencesTab: typeof import('./src/components/leads/tabs/PreferencesTab.vue')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    Tag: typeof import('primevue/tag')['default']
    Terminal: typeof import('primevue/terminal')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Tree: typeof import('primevue/tree')['default']
  }
}
